//! EP-17 census forecast — a short-horizon fan (median + 10/90 quantiles)
//! for hospital census, computed analytically from the sim's own generator
//! parameters. **Model-consistent by construction, and it says so**: expected
//! arrivals integrate the same λ(t) tables that drive [`crate::diurnal`] and
//! [`crate::edflow`]; expected departures apply the same LOS log-normals and
//! discharge-hour curve ([`crate::params`]) to the *standing census*,
//! conditioned on each patient's elapsed stay (EP-21 backdated stamps).
//!
//! What this deliberately is NOT:
//! - **Not an oracle.** The engine's event queue literally contains every
//!   scheduled discharge; the forecast never reads it. It sees only what a
//!   bed-huddle observer could see — who is in which bed, since when — and
//!   projects from the published tables. That is the demonstration: what a
//!   transparent statistical baseline can and cannot claim.
//! - **Not learned.** No fitting, no exogenous predictors (out of scope,
//!   EP-17 brief).
//! - **Not a forecast of hypotheticals.** It projects the live world only;
//!   EP-15 experiment arms are never forecast (scope fence).
//!
//! Known approximations, honestly listed (measured in `CALIBRATION.md`):
//! - Future **direct admits** are assumed not to exit within the horizon
//!   (F(24 h | fresh) < 1% on the day-scale LOS tables); future **ED
//!   arrivals** do churn out and are modeled as a thinned Poisson on the
//!   treat-and-release clock. Neglecting the ED churn was the first draft's
//!   +80-bed/day bias — the calibration replay caught it.
//! - Arrival uncertainty is taken as **Poisson** (variance = integrated λ).
//!   The generator thins arrivals per sub-step (`floor + Bernoulli`), which
//!   is *sub*-Poisson at coarse tick sizes — so the band errs conservative
//!   (wide). Coverage is measured, not assumed; see the calibration table.
//! - The discharge-hour curve enters twice, both as approximations of the
//!   generator's push-forward resample: its **mean delay** shifts the LOS
//!   clock (`F(x − 12.5 h)` — without it the model over-hazards the house by
//!   a measured −22 beds/day), and its **within-day shape** modulates the
//!   hazard proportionally (daily mass preserved, timing approximate).
//! - Capacity is a **clamp**, not a queueing model: quantiles cap at staffed
//!   beds. Turn-aways/diversion near saturation and surge injections are
//!   exactly where the simple model fails — documented, not hidden.
//! - Units with no flow process (psych, obs, L&D, nursery, …) and patients
//!   with no admit stamp project as **zero-flow** — consistent with the
//!   generator, which never moves them.
//!
//! Pure and RNG-free: same world + same instant ⇒ the same fan, bit for bit.

use crate::params::{self, LosParams};
use hupsim_core::index::HospitalIndex;
use hupsim_core::model::{Hospital, UnitType};

/// z for the 10th/90th percentile of a normal (Φ⁻¹(0.9)).
const Z_10_90: f64 = 1.281551565545;

/// 10–90 band coverage of 12 h-ahead forecasts (the displayed horizon) over
/// the settled regime of the committed calibration replay (seeded start,
/// seed 42, 8 sim-days, hourly issues — see `hupsim/CALIBRATION.md`,
/// regenerated by `hupsim-app/tests/forecast_calibration.rs`, which pins
/// this number to the measurement ±3%). Quoted wherever the fan is shown.
/// Above the nominal 80% because the Poisson arrival variance deliberately
/// errs conservative against the generator's sub-Poisson thinning.
pub const FAN_COVERAGE_10_90_PCT: f32 = 92.0;

/// Forecast inputs: horizon/grid plus the generator rates. Defaults mirror
/// [`crate::params`]; tests override rates to isolate flows.
#[derive(Debug, Clone, PartialEq)]
pub struct ForecastParams {
    pub horizon_min: f64,
    /// Grid step; 15 min matches the generator's λ sub-step and the timeline
    /// cadence, so the arrival integral is the generator's own.
    pub step_min: f64,
    pub admit_base_per_hr: f64,
    pub ed_base_per_hr: f64,
    pub ed_admit_fraction: f64,
}

impl Default for ForecastParams {
    fn default() -> Self {
        Self {
            horizon_min: 720.0,
            step_min: params::SUBSTEP_MIN,
            admit_base_per_hr: params::DIURNAL_BASE_ADMITS_PER_HR,
            ed_base_per_hr: params::ED_BASE_ARRIVALS_PER_HR,
            ed_admit_fraction: params::ED_ADMIT_FRACTION,
        }
    }
}

/// The fan: index 0 is "now" (all quantiles equal the current census), index
/// k is `issued_at_min + k·step_min`. Quantiles are clamped to
/// `[0, staffed_now]` — census cannot exceed staffed beds.
#[derive(Debug, Clone, PartialEq)]
pub struct CensusFan {
    pub issued_at_min: f64,
    pub step_min: f64,
    pub median: Vec<f32>,
    pub q10: Vec<f32>,
    pub q90: Vec<f32>,
    pub census_now: u32,
    /// Licensed minus out-of-service across the whole hospital (the clamp).
    pub staffed_now: u32,
    /// Expected arrivals over the full horizon (integrated λ, direct + ED).
    pub expected_in: f32,
    /// Expected departures over the full horizon (LOS/discharge tables
    /// applied to the standing census).
    pub expected_out: f32,
}

impl CensusFan {
    pub fn horizon_min(&self) -> f64 {
        (self.median.len().saturating_sub(1)) as f64 * self.step_min
    }
}

/// Abramowitz & Stegun 7.1.26 erf approximation (|ε| < 1.5e-7) — enough for
/// quantile work, no stats dependency.
fn erf(x: f64) -> f64 {
    let sign = if x < 0.0 { -1.0 } else { 1.0 };
    let x = x.abs();
    let t = 1.0 / (1.0 + 0.3275911 * x);
    let poly = t
        * (0.254829592
            + t * (-0.284496736 + t * (1.421413741 + t * (-1.453152027 + t * 1.061405429))));
    sign * (1.0 - poly * (-x * x).exp())
}

fn normal_cdf(x: f64) -> f64 {
    0.5 * (1.0 + erf(x / std::f64::consts::SQRT_2))
}

/// P(LOS ≤ `hr`) under the log-normal `p`.
fn lognormal_cdf(hr: f64, p: &LosParams) -> f64 {
    if hr <= 0.0 {
        return 0.0;
    }
    normal_cdf((hr / p.median_hr).ln() / p.sigma)
}

/// Per-step raw-hazard cap: a stay elapsed beyond the distribution's reach
/// projects as a prompt exit (the generator's own deep-tail fallback,
/// `sampling::residual_discharge_min`) instead of dividing 0/0.
const DEEP_TAIL_STEP_P: f64 = 0.995;

/// Mean forward push of the discharge-hour shaping
/// (`sampling::shape_discharge_min`): a tentative instant ~uniform in the
/// day is pushed to a weighted hour of the same or next day — mean delay
/// ≈ 12 h (+½ h intra-hour), and the generator *never* shortens a stay. The
/// inpatient LOS clock therefore runs on `F(x − delay)`; the delay's spread
/// (~hours) is negligible against the day-scale LOS σ. Without this shift
/// the model over-hazards the standing census by ~10% — the calibration
/// replay measured it as a −22 bed/day bias.
const DISCHARGE_SHAPING_MEAN_DELAY_HR: f64 = 12.5;

/// Compute the census fan for the standing census of `h` at `now_min`.
/// Pure, RNG-free, deterministic.
pub fn forecast_census(
    h: &Hospital,
    idx: &HospitalIndex,
    now_min: f64,
    fp: &ForecastParams,
) -> CensusFan {
    let n = (fp.horizon_min / fp.step_min).round().max(1.0) as usize;
    let dt_hr = fp.step_min / 60.0;

    // Discharge-hour modulation, normalized to mean 1.0 over the day so a
    // full-day integral preserves the LOS tables' daily mass.
    let wsum: f64 = params::DISCHARGE_HOUR_WEIGHTS.iter().sum();
    let hour_mod =
        |t_min: f64| params::DISCHARGE_HOUR_WEIGHTS[params::hour_of(t_min)] * 24.0 / wsum;

    // --- Expected departures: per-patient exit probability on the grid.
    let mut dep_mean = vec![0.0f64; n + 1];
    let mut dep_var = vec![0.0f64; n + 1];
    let mut census_now = 0u32;
    let mut staffed_now = 0u32;

    for room in &h.rooms {
        if !matches!(
            room.status,
            hupsim_core::model::RoomStatus::OutOfService { .. }
        ) {
            staffed_now += 1;
        }
        let Some(p) = room.status.patient() else {
            continue;
        };
        census_now += 1;
        let Some(&up) = idx.unit_pos.get(&room.unit) else {
            continue;
        };
        let unit = &h.units[up];

        if params::is_inpatient_unit(unit.unit_type) {
            // Departure = the service line's log-normal conditioned above the
            // elapsed stay, hazard-modulated by the discharge-hour curve.
            // Unknown stamps project zero-flow: the generator schedules no
            // exit for them either (BacklogDischarges skips them).
            let Some(admit_min) = p.admitted_at_min else {
                continue;
            };
            let elapsed_hr = ((now_min - admit_min) / 60.0).max(0.0);
            let los = params::los_for(unit.service_line.as_ref(), unit.unit_type);
            // Shifted clock: the discharge curve delays every exit (mean
            // ≈ 12.5 h past the raw draw) — see the const above.
            let shifted = elapsed_hr - DISCHARGE_SHAPING_MEAN_DELAY_HR;
            let mut survival = 1.0f64;
            let mut f_prev = lognormal_cdf(shifted, &los);
            for k in 1..=n {
                let f_next = lognormal_cdf(shifted + k as f64 * dt_hr, &los);
                let tail = 1.0 - f_prev;
                let p_raw = if tail < 1e-9 {
                    DEEP_TAIL_STEP_P
                } else {
                    ((f_next - f_prev) / tail).clamp(0.0, DEEP_TAIL_STEP_P)
                };
                let w = hour_mod(now_min + k as f64 * fp.step_min);
                survival *= (1.0 - p_raw).powf(w);
                f_prev = f_next;
                let q = 1.0 - survival;
                dep_mean[k] += q;
                dep_var[k] += q * (1.0 - q);
            }
        } else if unit.unit_type == UnitType::Ed && !p.boarding {
            // An ED occupant without an admit decision leaves the hospital
            // only on the treat-and-release branch. Being still in the bay at
            // elapsed e shifts the disposition posterior (Bayes over the two
            // episode log-normals); no discharge-hour shaping — ED releases
            // are unshaped in the generator.
            let anchor = p.admitted_at_min.unwrap_or(now_min).min(now_min);
            let elapsed_hr = (now_min - anchor) / 60.0;
            let af = fp.ed_admit_fraction;
            let f_rel_e = lognormal_cdf(elapsed_hr, &params::ED_TREAT_RELEASE_LOS);
            let f_dec_e = lognormal_cdf(elapsed_hr, &params::ED_DECISION_TO_ADMIT);
            let denom = af * (1.0 - f_dec_e) + (1.0 - af) * (1.0 - f_rel_e);
            for k in 1..=n {
                let q = if denom < 1e-9 {
                    // Both episode clocks exhausted: prompt exit on the
                    // prior release share.
                    1.0 - af
                } else {
                    let f_rel =
                        lognormal_cdf(elapsed_hr + k as f64 * dt_hr, &params::ED_TREAT_RELEASE_LOS);
                    ((1.0 - af) * (f_rel - f_rel_e) / denom).clamp(0.0, 1.0)
                };
                dep_mean[k] += q;
                dep_var[k] += q * (1.0 - q);
            }
        }
        // Boarders (admit decided, waiting for a bed) move within the
        // hospital, not out of it — their inpatient LOS restarts at
        // placement, far beyond a short horizon. Units with no flow process
        // (psych, obs, L&D, nursery, research, other) project zero-flow.
    }

    // --- Arrivals: the generator's own λ integral (direct + ED), evaluated
    // at step ends exactly like the ≤15-min process sub-steps. Future ED
    // arrivals also *leave* within a short horizon — the treat-and-release
    // share churns through in hours — so the in-house count of future
    // arrivals is a thinned Poisson: each ED arrival at step j is still in
    // house at step k with probability 1 − (1−af)·F_release(k−j). (Future
    // *direct* admits exit in-horizon with probability < 1% at 24 h — the
    // day-scale LOS tables put F(24 h | fresh) ≈ 0.006, and the discharge
    // curve only delays further — so their in-horizon exits are neglected.)
    // Thinned-Poisson variance equals its mean.
    let mut a_dir = vec![0.0f64; n + 1]; // per-step direct arrival mass
    let mut a_ed = vec![0.0f64; n + 1]; // per-step ED arrival mass
    let mut f_rel = vec![0.0f64; n + 1]; // F_release at multiples of Δ
    for k in 1..=n {
        let t = now_min + k as f64 * fp.step_min;
        a_dir[k] = params::diurnal_rate_per_hr(
            fp.admit_base_per_hr,
            &params::INPATIENT_ARRIVAL_SHAPE,
            params::WEEKEND_INPATIENT_FACTOR,
            t,
        ) * dt_hr;
        a_ed[k] = params::diurnal_rate_per_hr(
            fp.ed_base_per_hr,
            &params::ED_ARRIVAL_SHAPE,
            params::WEEKEND_ED_FACTOR,
            t,
        ) * dt_hr;
        f_rel[k] = lognormal_cdf(k as f64 * dt_hr, &params::ED_TREAT_RELEASE_LOS);
    }
    let af = fp.ed_admit_fraction;
    let mut lam_gross = vec![0.0f64; n + 1]; // arrivals in (the tooltip's "+in")
    let mut a_net = vec![0.0f64; n + 1]; // future arrivals still in house at k
    for k in 1..=n {
        lam_gross[k] = lam_gross[k - 1] + a_dir[k] + a_ed[k];
        let mut net = 0.0;
        for j in 1..=k {
            net += a_dir[j] + a_ed[j] * (1.0 - (1.0 - af) * f_rel[k - j]);
        }
        a_net[k] = net;
    }

    // --- Combine: census(t) = census(0) + net arrivals − standing-census
    // departures; arrival count is (thinned) Poisson — conservative vs the
    // generator's sub-Poisson thinning at coarse ticks — departures are
    // Poisson-binomial; normal quantiles.
    let c0 = census_now as f64;
    let cap = staffed_now as f64;
    let clamp = |v: f64| v.clamp(0.0, cap) as f32;
    let mut median = Vec::with_capacity(n + 1);
    let mut q10 = Vec::with_capacity(n + 1);
    let mut q90 = Vec::with_capacity(n + 1);
    for k in 0..=n {
        let mu = c0 + a_net[k] - dep_mean[k];
        let sd = (a_net[k] + dep_var[k]).sqrt();
        median.push(clamp(mu));
        q10.push(clamp(mu - Z_10_90 * sd));
        q90.push(clamp(mu + Z_10_90 * sd));
    }

    CensusFan {
        issued_at_min: now_min,
        step_min: fp.step_min,
        median,
        q10,
        q90,
        census_now,
        staffed_now,
        expected_in: lam_gross[n] as f32,
        // Standing-census exits plus the in-horizon exits of future ED
        // arrivals (gross − net), so "+in − out" always reconciles with the
        // median's endpoint.
        expected_out: (dep_mean[n] + (lam_gross[n] - a_net[n])) as f32,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testworld::world;
    use hupsim_core::ops;
    use hupsim_core::patient::{Acuity, Patient};

    fn zero_rates(horizon_min: f64) -> ForecastParams {
        ForecastParams {
            horizon_min,
            admit_base_per_hr: 0.0,
            ed_base_per_hr: 0.0,
            ..ForecastParams::default()
        }
    }

    fn pt(name: &str, admitted: Option<f64>, boarding: bool) -> Patient {
        Patient {
            id: name.into(),
            alias: name.into(),
            age: Some(50),
            service: None,
            admitted_at_min: admitted,
            acuity: Acuity {
                instability: 0.2,
                trend_per_hr: 0.0,
            },
            boarding,
            isolation: None,
            telemetry: false,
            note: String::new(),
        }
    }

    #[test]
    fn erf_and_cdf_match_known_values() {
        assert!((normal_cdf(0.0) - 0.5).abs() < 1e-7);
        assert!((normal_cdf(1.0) - 0.8413447).abs() < 1e-6);
        assert!((normal_cdf(-1.959964) - 0.025).abs() < 1e-6);
        let p = LosParams {
            median_hr: 96.0,
            sigma: 0.55,
        };
        assert!((lognormal_cdf(96.0, &p) - 0.5).abs() < 1e-9, "median ⇒ CDF ½");
        assert_eq!(lognormal_cdf(0.0, &p), 0.0);
    }

    /// Brief property 1: a zero-flow world projects a flat fan at the current
    /// census — no arrivals, no patients, no width.
    #[test]
    fn zero_flow_world_projects_flat_at_current_census() {
        let (h, idx) = world(&[("ms", hupsim_core::model::UnitType::MedSurg, 20)]);
        let fan = forecast_census(&h, &idx, 0.0, &zero_rates(1440.0));
        assert_eq!(fan.census_now, 0);
        assert!(fan.median.iter().all(|&v| v == 0.0));
        assert!(fan.q10.iter().all(|&v| v == 0.0));
        assert!(fan.q90.iter().all(|&v| v == 0.0));
        assert_eq!(fan.expected_in, 0.0);
        assert_eq!(fan.expected_out, 0.0);
    }

    /// Brief property 2: an arrivals-only world (no standing census, so no
    /// standing departures) rises by the integrated λ, *net* of the
    /// treat-and-release share of future ED arrivals churning back out —
    /// checked against an independent fine-grid integral of the same rate
    /// and release functions.
    #[test]
    fn arrivals_only_median_rises_by_integrated_lambda() {
        let (h, idx) = world(&[("ms", hupsim_core::model::UnitType::MedSurg, 2000)]);
        let fp = ForecastParams {
            horizon_min: 1440.0,
            ..ForecastParams::default()
        };
        let fan = forecast_census(&h, &idx, 0.0, &fp);

        // Independent net-arrivals integral at 1-min resolution: a direct
        // admit stays; an ED arrival at minute s is still in house at 24 h
        // with probability 1 − (1−af)·F_release(24 h − s).
        let horizon = 1440.0f64;
        let mut gross = 0.0f64;
        let mut expect_net = 0.0f64;
        for m in 0..1440 {
            let t = m as f64 + 1.0;
            let dir = params::diurnal_rate_per_hr(
                fp.admit_base_per_hr,
                &params::INPATIENT_ARRIVAL_SHAPE,
                params::WEEKEND_INPATIENT_FACTOR,
                t,
            ) / 60.0;
            let ed = params::diurnal_rate_per_hr(
                fp.ed_base_per_hr,
                &params::ED_ARRIVAL_SHAPE,
                params::WEEKEND_ED_FACTOR,
                t,
            ) / 60.0;
            let f_rel = super::lognormal_cdf((horizon - t) / 60.0, &params::ED_TREAT_RELEASE_LOS);
            gross += dir + ed;
            expect_net += dir + ed * (1.0 - (1.0 - fp.ed_admit_fraction) * f_rel);
        }
        let end = *fan.median.last().unwrap() as f64;
        assert!(
            (end - expect_net).abs() < expect_net * 0.015,
            "24 h median rise {end:.1} should match the fine net-λ integral {expect_net:.1}"
        );
        assert!(
            end < gross * 0.8,
            "the treat-and-release churn must be visible: net {end:.1} vs gross {gross:.1}"
        );
        // The tooltip decomposition reconciles with the median endpoint.
        assert!(
            ((fan.expected_in - fan.expected_out) as f64 - end).abs() < 0.5,
            "+in − out must reconcile with the median rise"
        );
        // And the band at the end is the thinned-Poisson ±1.28σ.
        let half = (fan.q90.last().unwrap() - fan.q10.last().unwrap()) as f64 / 2.0;
        let sd = expect_net.sqrt();
        assert!(
            (half - Z_10_90 * sd).abs() < 0.05 * Z_10_90 * sd,
            "band half-width {half:.2} vs thinned Poisson {:.2}",
            Z_10_90 * sd
        );
    }

    /// Brief property 3: the band widens with horizon. (Away from the
    /// staffed-capacity clamp — the clamp legitimately narrows a pinned
    /// band; that behavior is covered by `fan_clamps_at_staffed_beds`.)
    #[test]
    fn band_widens_with_horizon() {
        let (mut h, idx) = world(&[("ms", hupsim_core::model::UnitType::MedSurg, 800)]);
        for i in 0..20 {
            ops::admit(
                &mut h,
                &idx,
                &format!("ms.r{i}").into(),
                pt(&format!("p{i}"), Some(-60.0 * 30.0), false),
            )
            .unwrap();
        }
        let fan = forecast_census(&h, &idx, 0.0, &ForecastParams::default());
        let width = |k: usize| fan.q90[k] - fan.q10[k];
        for k in 1..fan.median.len() {
            assert!(
                width(k) >= width(k - 1) - 1e-4,
                "band must not narrow: step {k} {} < {}",
                width(k),
                width(k - 1)
            );
        }
        assert!(width(fan.median.len() - 1) > 1.0, "12 h band should be visibly wide");
    }

    /// Brief property 4: determinism — pure and RNG-free.
    #[test]
    fn same_world_same_fan() {
        let (mut h, idx) = world(&[("ms", hupsim_core::model::UnitType::MedSurg, 30)]);
        for i in 0..10 {
            ops::admit(
                &mut h,
                &idx,
                &format!("ms.r{i}").into(),
                pt(&format!("p{i}"), Some(-5000.0), false),
            )
            .unwrap();
        }
        let a = forecast_census(&h, &idx, 100.0, &ForecastParams::default());
        let b = forecast_census(&h, &idx, 100.0, &ForecastParams::default());
        assert_eq!(a, b);
    }

    /// Departures condition on the elapsed stay: a patient exactly at the
    /// table median has P(exit within 24 h) = (F(e+24)−F(e))/(1−F(e)) —
    /// hand-computed ≈ 0.315 for the med/surg fallback table. The
    /// discharge-hour modulation redistributes within the day but must
    /// preserve daily mass to within a few percent.
    #[test]
    fn departures_condition_on_elapsed_los() {
        let n = 40usize;
        let (mut h, idx) = world(&[("ms", hupsim_core::model::UnitType::MedSurg, 50)]);
        for i in 0..n {
            // Elapsed exactly the 96 h fallback median.
            ops::admit(
                &mut h,
                &idx,
                &format!("ms.r{i}").into(),
                pt(&format!("p{i}"), Some(-96.0 * 60.0), false),
            )
            .unwrap();
        }
        let fan = forecast_census(&h, &idx, 0.0, &zero_rates(1440.0));
        // Hand computation on the shifted clock (the discharge curve delays
        // every exit by ≈ 12.5 h): with s = 96 − 12.5 = 83.5,
        // q = (F(s+24) − F(s)) / (1 − F(s)) for the 96 h / σ 0.55 table.
        let f = |x: f64| normal_cdf((x / 96.0f64).ln() / 0.55);
        let s = 96.0 - DISCHARGE_SHAPING_MEAN_DELAY_HR;
        let q_expect = (f(s + 24.0) - f(s)) / (1.0 - f(s));
        let out = fan.expected_out as f64;
        assert!(
            (out - n as f64 * q_expect).abs() < 0.05 * n as f64,
            "expected {out:.1} exits vs hand-computed {:.1}",
            n as f64 * q_expect
        );
        // Median declines accordingly, and never rises with zero arrivals.
        let m = &fan.median;
        assert!(m.windows(2).all(|w| w[1] <= w[0] + 1e-4));
        assert!((m[0] - n as f32).abs() < 1e-6);
    }

    /// ED occupants: only the treat-and-release share departs, weighted by
    /// the disposition posterior; boarders project as staying (they move
    /// within the hospital). A fresh ED cohort with a full-horizon window
    /// departs ≈ (1 − admit fraction).
    #[test]
    fn ed_departures_follow_the_disposition_posterior() {
        let (mut h, idx) = world(&[("ed", hupsim_core::model::UnitType::Ed, 30)]);
        for i in 0..10 {
            ops::admit(
                &mut h,
                &idx,
                &format!("ed.r{i}").into(),
                pt(&format!("w{i}"), Some(0.0), false),
            )
            .unwrap();
        }
        for i in 10..15 {
            ops::admit(
                &mut h,
                &idx,
                &format!("ed.r{i}").into(),
                pt(&format!("b{i}"), Some(-300.0), true),
            )
            .unwrap();
        }
        let fan = forecast_census(&h, &idx, 0.0, &zero_rates(1440.0));
        // 10 fresh walk-ins × (1−0.30) release within 24 h (F_rel(24h) ≈ 1);
        // the 5 boarders contribute nothing.
        let expect = 10.0 * (1.0 - params::ED_ADMIT_FRACTION);
        assert!(
            (fan.expected_out as f64 - expect).abs() < 0.35,
            "expected ED exits {:.2} vs {expect:.2}",
            fan.expected_out
        );
    }

    /// Unknown-stamp patients and no-flow unit types project zero-flow —
    /// exactly like the generator, which never moves them.
    #[test]
    fn zero_flow_cohorts_project_flat() {
        let (mut h, idx) = world(&[
            ("ms", hupsim_core::model::UnitType::MedSurg, 5),
            ("ob", hupsim_core::model::UnitType::Obs, 5),
        ]);
        // Unknown stamp in an inpatient bed; deep-elapsed patient in obs.
        ops::admit(&mut h, &idx, &"ms.r0".into(), pt("legacy", None, false)).unwrap();
        ops::admit(&mut h, &idx, &"ob.r0".into(), pt("obs", Some(-9000.0), false)).unwrap();
        let fan = forecast_census(&h, &idx, 0.0, &zero_rates(720.0));
        assert_eq!(fan.expected_out, 0.0);
        assert!(fan.median.iter().all(|&v| (v - 2.0).abs() < 1e-6));
    }

    /// Quantiles clamp at staffed capacity — the model does not queue, it
    /// caps, and says so.
    #[test]
    fn fan_clamps_at_staffed_beds() {
        let (h, idx) = world(&[("ms", hupsim_core::model::UnitType::MedSurg, 10)]);
        // Absurd arrival rate into a 10-bed world.
        let fp = ForecastParams {
            horizon_min: 1440.0,
            admit_base_per_hr: 50.0,
            ed_base_per_hr: 0.0,
            ..ForecastParams::default()
        };
        let fan = forecast_census(&h, &idx, 0.0, &fp);
        assert_eq!(fan.staffed_now, 10);
        assert!(fan.q90.iter().all(|&v| v <= 10.0));
        assert!(*fan.median.last().unwrap() == 10.0);
    }
}
