//! Data provenance. Every structural assertion about HUP carries a confidence
//! grade and source so stale or inferred data stays separable from
//! directory-verified data — unit assignments at a real hospital churn, and
//! this model treats them as hypotheses.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum Confidence {
    /// Stated directly by an official Penn Medicine / Penn Facilities document.
    Verified,
    /// Stated by an official source that is undated or plausibly stale.
    Reported,
    /// Derived by reasoning across sources (e.g. room prefix → floor).
    Inferred,
    /// Plausible but unconfirmed.
    #[default]
    Unverified,
}

impl Confidence {
    pub fn label(self) -> &'static str {
        match self {
            Confidence::Verified => "verified",
            Confidence::Reported => "reported",
            Confidence::Inferred => "inferred",
            Confidence::Unverified => "unverified",
        }
    }
}

/// Which bed-map era an assertion belongs to. The Oct 2021 Pavilion opening
/// reshuffled most of HUP Main; pre-2021 unit assignments are historical.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum Era {
    PostPavilion,
    Pre2021,
    /// Physical structure — not era-dependent.
    Timeless,
    #[default]
    Unknown,
}

impl Era {
    pub fn label(self) -> &'static str {
        match self {
            Era::PostPavilion => "post-Pavilion (current era)",
            Era::Pre2021 => "pre-2021 (STALE — pre-Pavilion bed map)",
            Era::Timeless => "structural",
            Era::Unknown => "era unknown",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct Provenance {
    pub confidence: Confidence,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(default)]
    pub era: Era,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl Provenance {
    pub fn new(confidence: Confidence, source: impl Into<String>, era: Era) -> Self {
        Self {
            confidence,
            source: Some(source.into()),
            era,
            note: None,
        }
    }

    pub fn verified(source: impl Into<String>) -> Self {
        Self::new(Confidence::Verified, source, Era::Timeless)
    }

    pub fn synthetic() -> Self {
        Self {
            confidence: Confidence::Inferred,
            source: Some("synthetic (generated by hupsim)".into()),
            era: Era::Timeless,
            note: None,
        }
    }
}
